### ISSUE TITLE
Centered and Adjusted to Content Modal?

### ISSUE THREAD

**Issue by ramsestom** [pyliaorachel/react-native-listview-modal#1]
Hi
Is it possible to have a modal that automatically adjust its dimensions to the listview content and is centered on screen with  react-native-listview-modal? 
With react-native-list-popover it was the default behaviour but looking at the screenshots of your react-native-listview-modal component, It seems that the rendered Modal is fullscreen (maybe it is possible to change this behaviour with styling?)

**Comment by pyliaorachel** [comment]
Yes, you can.

The default styles are set in [container](https://github.com/pyliaorachel/react-native-listview-modal/blob/master/ListviewModal.js#L154) and [listView](https://github.com/pyliaorachel/react-native-listview-modal/blob/master/ListviewModal.js#L161), which are set to full screen height/width. As stated in [README](https://github.com/pyliaorachel/react-native-listview-modal#listviewmodal), you may pass in `containerStyle` and `listViewStyle` props to get rid of the default styling.

You might also want to set the [transparent prop in Modal](https://github.com/pyliaorachel/react-native-listview-modal/blob/master/Example/index.ios.js#L54) in the example to `true`, since `Modal` itself doesn't allow [much styling](https://facebook.github.io/react-native/docs/modal.html#presentationstyle) and will take up the whole screen. The alignments of the components will be up to you. 

Sorry the condition of my laptop now isn't quite well and I cannot test for you. Feel free to play around and tell me if it's possible.
